---
- name: WordBlitz Monitoring Setup
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - azure_subscription_id is defined and azure_subscription_id != "your-subscription-id-here"
          - azure_resource_group is defined
          - azure_location is defined
          - law_name is defined
          - grafana_name is defined
          - db_vm_name is defined
          - app_vm_name is defined
          - db_vm_host is defined
          - app_vm_host is defined
          - ssh_user is defined
          - db_vm_computer_name is defined
          - app_vm_computer_name is defined
          - app_vm_perf_computer_name is defined
        fail_msg: >-
          Required variables are not set. Copy group_vars/all.yml.example to
          group_vars/all.yml and fill in your values.

  tasks:
    - name: Create Grafana instance (started early — provisioning takes several minutes)
      ansible.builtin.include_role:
        name: grafana
        tasks_from: create_instance
      tags: [grafana]

    - name: Set up Log Analytics Workspace
      ansible.builtin.include_role:
        name: log_analytics
      tags: [log_analytics]

    - name: Configure VM managed identities
      ansible.builtin.include_role:
        name: vm_identity
      tags: [vm_identity]

    - name: Install Azure Monitor Agent
      ansible.builtin.include_role:
        name: azure_monitor_agent
      tags: [azure_monitor_agent]

    - name: Set up Data Collection Rule
      ansible.builtin.include_role:
        name: data_collection_rule
      tags: [data_collection_rule]

    - name: Configure VM syslog forwarding
      ansible.builtin.include_role:
        name: vm_logging
      tags: [vm_logging]

    - name: Configure Grafana data source and deploy dashboard
      ansible.builtin.include_role:
        name: grafana
        tasks_from: configure
      tags: [grafana]
